### ISSUE TITLE
John Ryan feedback

### ISSUE THREAD

**Issue by csells** [csells/go_router#1]
hey, @johnpryan. I'd love your feedback on the current state of the go_router.

**Comment by johnpryan** [comment]
Hey, here's some initial feedback:
- I like that the implementation is simple and small. 
- Initially, I wasn't sure why `GoRouter.routes` took a builder. Why not just a list of routes? It looks like the idea is that you can prevent the user from accessing routes by changing the the list of _possible routes_  depending on whether or not the user is logged in or out?
- The end-user still has to parse the URL parsing manually in `example/lib/builder.dart`. I'm wondering how to make this scale better for big apps, or if there's a better way.
- How does `GoRouter.routes` determine the pages to return for a location? For example if I configure three GoRoutes like `/`, `/family` and `/family/:fid`, will the pages for `/` and `/family` be included when `/family/5` is the current route since their characters are a prefix for `/family/5`? 
- Could this API be used to implement the nested routing scenario from the [flutter/uxr storyboards](https://github.com/flutter/uxr/blob/master/nav2-usability/storyboards/%5BPublic%5D%20Flutter%20Navigator%20Scenarios%20Storyboards%20v2.pdf). A good test case would be a bottom navigation bar with an inner TabBarView. It looks like the rest of the scenarios are supported already.
- It might be interesting to see how [hierarchical route configurations](https://github.com/flutter/uxr/issues/35) could work with this API. This is useful for scalability reasons, two or more developers might want to configure routes for certain sub-paths like `/family` and `/settings` and compose them together.

**Comment by csells** [comment]
@johnpryan thanks for the feedback! My replies below:

> Initially, I wasn't sure why GoRouter.routes took a builder. Why not just a list of routes? It looks like the idea is that you can prevent the user from accessing routes by changing the the list of possible routes depending on whether or not the user is logged in or out?

that's right -- you need a builder to get a callback when data changes via an IW. check out [the Conditional Routes section](https://github.com/csells/go_router#conditional-routes) for details.

> The end-user still has to parse the URL parsing manually in example/lib/builder.dart. I'm wondering how to make this scale better for big apps, or if there's a better way.

That's just an example of the base functionality, i.e. go_router takes care of all of the protocol; you just have to implement this one method (the builder) that takes in a URI-based location and produces a `Navigator`. If you want to do things in a declarative way, you can use `GoRouter.routes`. Was that unclear in the README?

> How does GoRouter.routes determine the pages to return for a location? For example if I configure three GoRoutes like /, /family and /family/:fid, will the pages for / and /family be included when /family/5 is the current route since their characters are a prefix for /family/5?

That's correct. That's simplifying assumption #2: "an entire stack of pages can be constructed from the route name alone". `GoRouter.routes` matches all of the patterns and creates the stack of pages from everything that matches.

> Could this API be used to implement the nested routing scenario from the flutter/uxr storyboards. A good test case would be a bottom navigation bar with an inner TabBarView. It looks like the rest of the scenarios are supported already.

I haven't implemented support for nested routes yet. You had mentioned that you were interested in submitting a PR w/ a nested route implementation. I plan to get to that once I've done the other pieces if you don't get to it first.

> It might be interesting to see how hierarchical route configurations could work with this API. This is useful for scalability reasons, two or more developers might want to configure routes for certain sub-paths like /family and /settings and compose them together.

I'm not familiar w/ that term. Is that also something you'd like to contribute? Or if not, point me at a definition so I can implement it?

**Comment by csells** [comment]
dup: https://github.com/csells/go_router/issues/4
