### ISSUE TITLE
Combining context.goNamed with an AutofillGroup breaks TextField's "autofocus" on iOS

### ISSUE THREAD

**Issue by Lootwig** [csells/go_router#317]
Running the code below on flutter 2.8.1 in iOS 15.2 on the Simulator results in the keyboard closing immediately after navigating to the `Second` page.

The behavior does not occur
- when replacing `goNamed` with `Navigator.of(context).push(MaterialPageRoute<void>(builder: (_) => const Second()))`
- or when removing the `AutofillGroup` on `First`.

<details>
<summary>Minimum working example</summary>

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  MyApp({Key? key}) : super(key: key);

  final _router = GoRouter(
    routes: [
      GoRoute(
        path: '/',
        builder: (_, __) => const Home(),
        routes: [
          GoRoute(
            name: '2',
            path: '2',
            builder: (_, __) => const Second(),
          ),
          GoRoute(
            name: '1',
            path: '1',
            builder: (_, __) => const First(),
          ),
        ],
      ),
    ],
  );

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routeInformationParser: _router.routeInformationParser,
      routerDelegate: _router.routerDelegate,
    );
  }
}

class Home extends StatefulWidget {
  const Home({Key? key}) : super(key: key);

  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ElevatedButton(
          onPressed: () => context.goNamed('1'),
          child: const Center(child: Text('To First')),
        ),
      ),
    );
  }
}

class First extends StatelessWidget {
  const First({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            ElevatedButton(
              onPressed: () => context.goNamed('2'),
              child: const Text('To Second'),
            ),
            const AutofillGroup(child: SizedBox()),
          ],
        ),
      ),
    );
  }
}

class Second extends StatelessWidget {
  const Second({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(child: TextFormField(autofocus: true)),
    );
  }
}

```
</details>

Video (doesn't show in browser for me, but can be downloaded when copying address):

https://user-images.githubusercontent.com/39827040/149756670-80fb21ba-77dd-4ce0-8681-4a8a33bc47eb.mov

**Comment by csells** [comment]
That's strange. @lulupointu can you think of anything that might be causing that behavior?

**Comment by lulupointu** [comment]
I did not but I investigated and I think this is because of `AutofillGroup.dispose` which calls `TextInput.finishAutofillContext` which removes the keyboard focus.

It's not that `autofocus` does not work (you can actually see the textfield being focus during a few frames), it's rather that `autofocus` acts before `TextInput.finishAutofillContext`.

### Why replacing `goNamed` with `Navigator.of(context).push(MaterialPageRoute<void>(builder: (_) => const Second()))` works ?

When you do `Navigator.of(context).push` it pushes on top of the `First` widget. Therefore the `First` widget is not disposed which means that `TextInput.finishAutofillContext` is **not** called so `autofocus` works.

### Why removing the `AutofillGroup` on `First` works?

As I said, the problematic part is `TextInput.finishAutofillContext` which is called in `AutofillGroup.dispose` so removing `AutofillGroup` does the trick.

### How to fix this?

The solution I found was to manually refocus the first time the `TextField` is unfocused. The issue is that if you navigate to `Second` from a screen which does not have a `AutofillGroup.dispose`, then the first manual keyboard focus will be ignore. Maybe a timer to remove the listener might be good enough. Definitely not perfect though

Here is my `Second` implementation:

```dart
class Second extends StatefulWidget {
  const Second({Key? key}) : super(key: key);

  @override
  State<Second> createState() => _SecondState();
}

class _SecondState extends State<Second> {
  final _focusNode = FocusNode();

  @override
  void initState() {
    super.initState();
    // Focus after un-focus
    _focusNode.addListener(_refocusPlease);
  }

  _refocusPlease() {
    if (!_focusNode.hasFocus) {
      _focusNode.nextFocus();
      _focusNode.removeListener(_refocusPlease);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: TextFormField(focusNode: _focusNode, autofocus: true),
      ),
    );
  }
}
```

Also I tried a few things like `WidgetsBinding.instance.addPostFrameCallback` but this did not work. I think this is because of how `Navigator` works (when a screen is removed, it is not removed directly but stays a few frames inside the widget tree to allow its out animation if any)

**Comment by csells** [comment]
@Lootwig does you confirm that this solves your problem?

@lulupointu thanks!

**Comment by Lootwig** [comment]
@lulupointu thanks for looking into it, but the suggested implementation for `Second` does not work very well:
- on an M1 iPhone 13 simulator, it does not change the behavior
- on Android, where the problem does not occur for whatever reason, it would block any *intentional* unfocusing (e.g. I just tested this with a second text field on the same page, which, of course, only focuses when tapped twice)

@csells even if it's not a solution, I understand that this is not a GoRouter issue. Would appreciate your upvotes over at https://github.com/flutter/flutter/issues/96756!
