### ISSUE TITLE
provide for multiple navigation stacks?

### ISSUE THREAD

**Issue by csells** [csells/go_router#82]
e.g. https://medium.com/coding-with-flutter/flutter-case-study-multiple-navigators-with-bottomnavigationbar-90eb6caa6dbf

**Comment by rydmike** [comment]
The iOS style nested state keeping bottom navigation pattern is one that is often asked for when talking about nested navigation.

I wonder if it can't be built already  with current version and some tiny bit of extra Flutter code. I might try it later.

**Comment by csells** [comment]
Thanks, @rydmike . I'm looking forward to what you come up with.

**Comment by KristianBalaj** [comment]
I'm focusing on this feature (and on the nested navigation in general) in my package [routeborn](https://pub.dev/packages/routeborn).

When there is a nested navigation, the navigation stack is branching into multiple navigation stacks like a tree. Currently the implementation is in a way of single source of truth regarding the navigation stacks (the SSOT is the `NavigationNotifier` in my package). The `NavigationNotifier` is managing all the stacks.

Since the branching analogy, a method for changing branches in nested navigation is the `setNestingBranch` method, where by default the navigation stacks are preserved.
In case a user doesn't want the stack preservance feature, there is an optional parameter `bool resetBranchStack`.

**Comment by esDotDev** [comment]
I think go_router does everything it can do to implement this feature, it can't really be implemented "out of the box", the flutter developer needs to do a little bit of extra lifting. 

This is because go_router is path based, there is fundamentally no such thing as 'multiple stacks' ever in memory. There is simply a path, and that will match to some sub-set of pages, and you can wrap those pages in an external tab menu, which gets you most of the way to nested nav in appearence, just not in behavior.

What's left to do, is the key feature people expect from this paradigm which is "each tab preserves it's state".  This breaks down into 2 parts as far as I see:
* Restore the correct page when switching to a tab (it should load the page it was showing previously, and remember the viewstack)
* Have the page itself remember it's state (scroll position, selected sort options, etc)

The first thing can be done by having some imperative code that saves off the last viewed path for each tab, and when the tab is pressed, it tries to look up the last known page, and show that rather than the default. For example, the default url for tab1 might be `/tab1/messages` but it could link instead `/tab1/messages/compose` if that was the last recorded path for tab1. Given that later path, GoRouter would be smart enough to stack the `Compose` page on top of `Messages` and pop() would work as expected.

The second requirement is harder, having the stateful views remember/restore their state. I don't think there is actually a good solution for this that will work with GoRouter, unless you just have 1 "pageRoute" and all routing is handled internally in that page. The `Restoration` API could be extended to serve this use case I think. In the meantime it would probably have to be done via some form of persistent storage and having views manually restore their state when loaded, using an id (just like Restoration API does).

**Comment by davidmartos96** [comment]
> I think go_router does everything it can do to implement this feature, it can't really be implemented "out of the box", the flutter developer needs to do a little bit of extra lifting. 
> 
> This is because go_router is path based, there is fundamentally no such thing as 'multiple stacks' ever in memory. There is simply a path, and that will match to some stack of pages, and you can wrap those pages in an external tab menu, which gets you most of the way to nested nav in appearence, just not in behavior.
> 
> What's left to do, is the key feature people expect from this paradigm which is "each tab preserves it's state".  This breaks down into 2 parts as far as I see:
> * Restore the correct page when switching to a tab (it should load the page it was showing previously, and remember the viewstack)
> * Have the page itself remember it's state (scroll position, selected sort options, etc)
> 
> The first thing can be done by having some imperative code that saves off the last viewed path for each tab, and when the tab is pressed, it tries to look up the last known page, and show that rather than the default. For example, the default url for tab1 might be `/tab1/messages` but it could link instead `/tab1/messages/compose` if that was the last recorded path for tab1. Given that later path, GoRouter would be smart enough to stack the `Compose` page on top of `Messages` and pop() would work as expected.
> 
> The second requirement is harder, having the stateful views remember/restore their state. I don't think there is actually a good solution for this that will work with GoRouter, unless you just have 1 top level pageRoute and all subsequent page routing is handled internally inside that widget. In theory the `Restoration` API could be extended to serve this use case I think. In the meantime it would probably have to be done via some form of persistent storage and having views manually restore their state when loaded, using an id (just like Restoration API does). 

Couldn't that second requirement be accomplished with Offstage widgets and a Stack? (As described in the article at the top) That way when switching tabs the state wouldn't be lost.

**Comment by esDotDev** [comment]
Ya, that's basically what I mean with "_1 top level pageRoute and all subsequent page routing is handled internally inside that widget_", like GoRouter is mapped to one persistent route, and an IndexedStack or something is handling the page-routing from there somehow? But then GoRouter is not doing much, except parsing some args for us and updating the browser location.

It's worth noting too, if you can access the navigation path history, then it's pretty trivial to have these menu buttons that know they are "/tab1", and can either link to their default path, or look up the last history location that contained their path. So that part is not really as cludgy as it sounds and you end up with the UX most clients seem to want.

**Comment by csells** [comment]
I'd love a sample of that...

**Comment by esDotDev** [comment]
I do have a lib I made for almost this exact purpose https://pub.dev/packages/path_stack

It just wraps `IndexedStack`, but uses strings as keys instead of int, and supports nesting:
https://pub.dev/packages/path_stack

I'll see what I can do for a little demo of combining this with `GoRouter` :)

**Comment by csells** [comment]
Nice!

**Comment by esDotDev** [comment]
Thinking about it a bit more, my worry is that I don't think this is the right direction for GoRouter. We'd we'd lose all the nice stacking logic you have, and have to reproduce most of the path parsing logic. 

Seems like the better approach is to just try and remember tabs, and restore page state manually somehow. It's a bit harder, but then everything should just click together.

**Comment by csells** [comment]
is there some of the useful bits of GoRouter that can be exposed to implement this functionality?

**Comment by esDotDev** [comment]
As long as you expose the history of paths, then the tab btn stuff should be pretty trivial. 

Restoration is the hard one,  This line from the docs is interesting:
_In addition to providing restoration data when the app is launched, restoration data may also be provided to a running app to restore it to a previous state (e.g. when the user hits the back/forward button in the web browser). When this happens, the RestorationManager notifies its listeners (added via addListener) that a new rootBucket is available. In response to the notification, listeners must stop using the old bucket and restore their state from the information in the new rootBucket._

If we could somehow trigger that restoration call each time we change routes, I think in theory we could get the "Stateful Tabs" paradigm working pretty neatly.

**Comment by csells** [comment]
I'm not sure what you mean by "history of paths". Do you mean the stack of routes that a location creates? Those trivial to expose.

**Comment by esDotDev** [comment]
I guess I should have said history of locations. The equivalent of your browser history. A list of strings, representing the chronological history of your current browsing session. 

This would allow each tab to effectively "remember" it's last visited child page by just looking at the history, and checking for the most recent location, and loading that when the tab is pressed.

If you don't expose this, if would be easy enough to listen to the router, and record each new location as it comes in allowing us to generate this history stack manually. Nice if it were exposed though.

**Comment by csells** [comment]
go_router doesn't track this info. you can listen to changes on the `GoRouter` and pull out the `location` property as it changes.

**Comment by esDotDev** [comment]
Ok, ya as I mentioned I know goRouter is a changeNotifier, so we could always listen to it and do it manually. 

Would be nice if it maintained this state though, since it's quite useful to be able to peer into history stack and do stuff with it, like we just demonstrated :D

**Comment by esDotDev** [comment]
VRouter provides something like this: https://pub.dev/documentation/vrouter/latest/vrouter/VHistory-class.html so these use cases are made a little easier.

**Comment by esDotDev** [comment]
Any thoughts on the more difficult aspect which is having routes be able to restore their state when loaded?

I wonder if there is some way we can trigger `RestorationManager` to run when a new route is shown, so we have a nice clean mechanism for routes to restore their state?

**Comment by csells** [comment]
Maybe we implement the UX first and then get the state restoration working after?

**Comment by aytunch** [comment]
> I do have a lib I made for almost this exact purpose https://pub.dev/packages/path_stack
> 
> It just wraps `IndexedStack`, but uses strings as keys instead of int, and supports nesting: https://pub.dev/packages/path_stack
> 
> So all the pages are just kept in memory for free. I'll see what I can do for a little demo of combining this with `GoRouter` :)

@esDotDev 
If we have Google maps with lots of markers in one of the bottom nav tabs and a video feed on another, etc, the `Offstage` + `IndexedStack` strategy to keep state would consume a lot of memory right? When you said "memory for free", I wonder if there is something I am missing from the picture Maybe Flutter does something clever behind the scenes? Because I sure don't want to keep the restoration states of all my pages manually.

**Comment by esDotDev** [comment]
Yep, we're trading RAM for improved UX in this case. "memory for free", I just mean that the routes are cached in ram, so no extra work is needed for the dev, and all state is maintained, from viewstate to internal scroll state etc.

In my `pathStack` lib, I make it optional, so a route could say that it doesn't want to be persistent or not, so maybe you'd set the video view to be non persistent, and instead do a manual restoration on that page.

**Comment by esDotDev** [comment]
Some digging this morning turned up this very interesting looking API:
https://api.flutter.dev/flutter/widgets/Navigator/restorablePush.html there is nothing on all of the internet about how to use it though. Guess it's time to play :)

**Comment by aytunch** [comment]
@esDotDev this is great find. If `RestorablePush` can be implemented in `go_router` with a simple API, then this could be a game changer. We can easily choose which pages we want to be restorable and even dynamically change them if needed (If user is too deep in a nested route)

**Comment by esDotDev** [comment]
Turns out there is an old API `PageStorage` that I was unaware of, this should allow us to restore route state with a bit of work. So I think this + a little imperative code for the tab buttons should get the job done! Albeit it in a slightly cumbersome way. Things will need to be assigned keys and each stateful view is responsible for saving/loading it's own state, but I imagine some helper classes could ease this quite a bit... 
https://api.flutter.dev/flutter/widgets/PageStorage-class.html

 RestorableRoutes I think is more for restoring whatever arguments you had passed into the route? Which might be something go_router wants to support internally? I'm not sure...

**Comment by csells** [comment]
if we can have a sample of it working with go_router today, then we can evaluate what we'd want to push into go_router to make the scenario easier

**Comment by esDotDev** [comment]
Ok put together a working sample here, it uses a combination of imperative logic to find the most recent sub-path for a given tab, and also the PageStorage API to allow each route to restore it's state:
https://github.com/esDotDev/flutter_experiments/tree/master/gorouter_with_stored_tabs

https://user-images.githubusercontent.com/736973/139731436-c3357ed9-0157-4ccc-b3ca-6a2eb36ecf3a.mp4

You can see an example of how to manually save/restore state using a bucket here:
https://github.com/esDotDev/flutter_experiments/blob/master/gorouter_with_stored_tabs/lib/demo_pages/messages_page.dart

And how to use PageStorage API to restore scroll positions here: 
https://github.com/esDotDev/flutter_experiments/blob/master/gorouter_with_stored_tabs/lib/demo_pages/feed_page.dart

The 'smart tab btns', just work like this:
```
void _handleBtnPressed(GoRouter router) {
    // Assume we're going to link to our basePath which is the common case
    String newPath = basePath;
    // If we're not currently selected, attempt to restore the last page the user was viewing for this tab.
    bool isNotSelected = router.location.contains(basePath) == false;
    if (isNotSelected) {
      // Look for most recent location that contains our basePath.
      bool match(String s) => s.contains(basePath);
      String mostRecentSubPage = App.locationHistory.firstWhere(match, orElse: () => '');
      // If we found a match, use it. Otherwise fall back to the basePath.
      if (mostRecentSubPage.isNotEmpty) {
        newPath = mostRecentSubPage;
      }
    }
    router.go(newPath);
  }
  ```

**Comment by esDotDev** [comment]
In terms of what go_router could do to make this easier, a couple thoughts come to mind:
* Could provide a list of location history so devs don't have to build it themselves, and pass it around the tree using provider or a global variable.
* Could provide an API for getting the various pageStorage keys, to make this a little easier, as when using `PageStorage` typically need a unique key that is a combination of the current path + field name:
```
pageBucket.writeState(context, _count, identifier: goRouter.getPageStorageKey('_count'));
// or
ListView(key: goRouter.getPageStorageKey('list1')),
```

**Comment by aytunch** [comment]
@esDotDev this looks awesome. And thanks for the video illustration.
In the 57th second of the video when we go from messages tab to the feed tab(while feed settings is open), we first see the feed page and also see the transition animation of the feed settings page being pushed. Is there a way to directly see the page which is on the top pf the stack with this method?

**Comment by esDotDev** [comment]
Ya that's a bug because I wasn't properly assigning page keys, but I was too lazy to re-record. It works properly when page keys are assigned:

https://user-images.githubusercontent.com/736973/139758914-017ea456-02e5-4402-b7fc-1bb78b546b69.mp4

**Comment by esDotDev** [comment]
Intersting comment in the src code here:
![image](https://user-images.githubusercontent.com/736973/139776610-b59f5e7d-93d8-40db-9bc7-d410fa05d09a.png)

Seems like I wasn't too far off thinking restoration could be used for this. It seems very similar to the PageStorage API. I'm just not sure how it works, like how do views request state restoration to happen when a new route is pushed?

**Comment by esDotDev** [comment]
Unfortunately it seems all flutter `PageRoute` extend `ModalRoute`, which add a `PageStorage` element, and no ability for you to provide your own bucket. 

This means it's not possible for use to provider a single PageStorage outside the Navigator, as the views will never find it. `PageStorage.of(context)`, will always return the one from the route, not the one at the top of the tree that we want for persistent storage.

Not a deal breaker, but it means each toplevel page view that wants to restore it's children needs to add some boilerplate like:
```
return PageStorage(
  bucket: GoRouter.of(context).storage.bucket,
  ....
)
```
Seems like restoration will be a better end-solution, as `PageStorage` is a little problematic. It has this rather major limitation, and also has some pretty nasty edge cases because of some odd design decisions: https://github.com/flutter/flutter/issues/53040

**Comment by esDotDev** [comment]
Thinking more about how GoRouter can support "stateful routes" in general, without needing any restoration/storage hassles, it fundamentally comes down to: **_can you cache the results of `pageBuilder`_ so that next time that same route is built, we get the cached version with intact state.**

I think that comes down to a question of whether the child-widget of a `Page` can be cached somehow. Normally you would cache views like this with a `Stack` of `Offstage` widgets, but I'm not sure how to make that work when working with Pages. 

If you can have stateful routes, and you can use a bit of logic to remember the last viewed page for any stack, then I think you get a really elegant implementation of the "multiple nav stacks" paradigm, with full browser support.

Also, fwiw, I have logged an issue last April requesting support for this use case w/ Restoration
https://github.com/flutter/flutter/issues/80303

**Comment by esDotDev** [comment]
I created an issue specifically to discuss state preservation of routes, cause it's really it's own feature. 

Curious if anyone has any bright ideas on this problem in particular:
https://github.com/csells/go_router/issues/134

**Comment by davidmartos96** [comment]
I've created a small demo of a persistent bottom navigation with independent routes and helper methods to navigate across different tabs (similar to how the Play Store Console behaves with its Navigation Rail).

I don't know how feasible would be for `go_router` to implement something like this out of the box. This approach uses IndexedStack which persists the different children states in memory.

https://github.com/davidmartos96/go_router_bottom_nav_demo/tree/main/lib

**Comment by olof-dev** [comment]
For reference, in addition to Andrea Bizzotto's article mentioned at the start, there's also Hans Muller's take on nested navigation:
https://medium.com/flutter/getting-to-the-bottom-of-navigation-in-flutter-b3e440b9386

**Comment by techouse** [comment]
> https://github.com/davidmartos96/go_router_bottom_nav_demo/tree/main/lib

Thanx for the idea of using a provided router delegates @davidmartos96 💟 I've implemented this approach in combination with a `PageView` and `AutomaticKeepAliveClientMixin` on the screens themselves and it works as expected. 👍🏻

**Comment by csells** [comment]
fyi @lulupointu on these approaches

**Comment by lulupointu** [comment]
@csells yes I've read these before designing the [Multi stack API](https://github.com/csells/go_router/discussions/222). 

State restoration would not be at the level that @esDotDev (since this would means caching every visited page). However the API uses `IndexedStack` (a lazy version actually) under the hood so switching between tabs would keep the state of the others (as described in the doc). So [this](https://github.com/csells/go_router/issues/82#issuecomment-991569591) and [that](https://github.com/csells/go_router/issues/82#issuecomment-980614094) would be possible.

**Comment by bahag-raesenerm** [comment]
@esDotDev how is the current state of this topic?
we'd really like to go with go_router but need this functionality ... we could also consider "to hack it" for a temporary solution but maybe we could also contribute somehow to bring things forward?

**Comment by johnpryan** [comment]
There are definitely some cases where using a nested Navigator makes sense (see [Hans' article](https://medium.com/flutter/getting-to-the-bottom-of-navigation-in-flutter-b3e440b9386) for an example). But I wonder if we should recommend configuring the inner Navigator using the `page` parameter based off of GoRouterState, since that is more declarative.

**Comment by johnpryan** [comment]
Here's a [gist](https://gist.github.com/johnpryan/b775521ab2d10987afe2bac284cf11d0) that shows what I mean. The app uses a BottomNavigation bar and an AnimatedSwitcher to set up lateral navigation between two screens. The first screen [(](LibraryScreen) builds a nested Navigator with the `pages` parameter. When the route is `/`, it displays a single page, but when the route is `/song/:songId` it's `songId` field is non-null, and an additional page is provided to the inner Navigator to show the SongScreen too:

```
class LibraryScreen extends StatelessWidget {
  final String? songId;

  const LibraryScreen({
    this.songId,
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    // Use a local variable to promote to a non-nullable type
    final songId = this.songId;

    return Navigator(
      onPopPage: (route, dynamic result) {
        final didPop = route.didPop(result);
        if (didPop) {
          // The user isn't viewing the song screen anymore. Go to the
          // parent screen.
          GoRouter.of(context).go('/');
        }
        return didPop;
      },
      pages: [
        MaterialPage(
          child: Scaffold(
            appBar: AppBar(),
            body: Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Text(
                    'Home Screen',
                    style: Theme.of(context).textTheme.headline4,
                  ),
                  TextButton(
                    onPressed: () {
                      GoRouter.of(context).go('/song/123');
                    },
                    child: const Text('View song 123'),
                  ),
                ],
              ),
            ),
          ),
        ),
        if (songId != null) MaterialPage(child: SongScreen(songId: songId))
      ],
    );
  }
}
```

The problem is that once the user taps the "recents" tab in the BottomNavigationBar, the previous route might have been `/song/1`, and there's no obvious way to use go_router to store this state, but I'm not sure if it should.

**Comment by csells** [comment]
The scenario that I get asked about all the time is for a tabbed ui (whether on the top or the bottom) to have a nav stack per tab and that switching between tabs should remember the users spot in the nav stack for each tab. I've come to understand that this is what "nested nav" means to people and it's a common app requirement that go_router should support.

**Comment by II11II** [comment]
> I've created a small demo of a persistent bottom navigation with independent routes and helper methods to navigate across different tabs (similar to how the Play Store Console behaves with its Navigation Rail).
> 
> I don't know how feasible would be for `go_router` to implement something like this out of the box. This approach uses IndexedStack which persists the different children states in memory.
> 
> https://github.com/davidmartos96/go_router_bottom_nav_demo/tree/main/lib

Hi @davidmartos96 
Thank you for good idea, but app loses deep link functionality
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/45257709/153729923-91740057-9fa8-49ec-a879-af12119dedfb.png">

**Comment by esDotDev** [comment]
> The problem is that once the user taps the "recents" tab in the BottomNavigationBar, the previous route might have been `/song/1`, and there's no obvious way to use go_router to store this state, but I'm not sure if it should.

Right, this is one of the core pieces of logic provided by lulu's tabbed router example. _Someone_ needs to remember what was the last visited url for each tab, so that when the tab is clicked, it can link into the last loaded url for that tab (or fallback to the "home tab")

**Comment by mark8044** [comment]
Thanks for everyone work on this issue.  Solving this would make go_router _the_ router to use.

One issue with other implementations of BottomNavigation and IndexedStacks is that on iOS you lose access to the scroll-to-top with status bar tap functionality.  This is because of issues with the PrimaryScrollController from a root stack eating up those clicks.  And if you try to pass PSC to all the different stacks then they all scroll up.

So far using CupertinoTabScaffold/CupertinoTabBar doesn't seem to carry the problem (but has so many other problems with routers).

Just throwing this out there as something to keep in mind with your implementations.  If its working with your implementation, then mores the better!

On the edge of my app to see if this comes to go_router as everything else seems to work really well and _easy_

**Comment by techouse** [comment]
@mark8044 Yeah, I've faced the same issue and just done what Facebook does in their app. A repeated tap on the currently active bottom nav takes you back to the top 🤷

**Comment by davidmartos96** [comment]
> Thanks for everyone work on this issue.  Solving this would make go_router _the_ router to use.
> 
> One issue with other implementations of BottomNavigation and IndexedStacks is that on iOS you lose access to the scroll-to-top with status bar tap functionality.  This is because of issues with the PrimaryScrollController from a root stack eating up those clicks.  And if you try to pass PSC to all the different stacks then they all scroll up.
> 
> So far using CupertinoTabScaffold/CupertinoTabBar doesn't seem to carry the problem (but has so many other problems with routers).
> 
> Just throwing this out there as something to keep in mind with your implementations.  If its working with your implementation, then mores the better!
> 
> On the edge of my app to see if this comes to go_router as everything else seems to work really well and _easy_

I haven't tried, but couldn't you wrap every tab with a Primary scroll controller widget and pass a different controller to each tab?

**Comment by mark8044** [comment]
> > Thanks for everyone work on this issue.  Solving this would make go_router _the_ router to use.
> > One issue with other implementations of BottomNavigation and IndexedStacks is that on iOS you lose access to the scroll-to-top with status bar tap functionality.  This is because of issues with the PrimaryScrollController from a root stack eating up those clicks.  And if you try to pass PSC to all the different stacks then they all scroll up.
> > So far using CupertinoTabScaffold/CupertinoTabBar doesn't seem to carry the problem (but has so many other problems with routers).
> > Just throwing this out there as something to keep in mind with your implementations.  If its working with your implementation, then mores the better!
> > On the edge of my app to see if this comes to go_router as everything else seems to work really well and _easy_
> 
> I haven't tried, but couldn't you wrap every tab with a PrimaryScrollController widget and pass a different controller to each tab?

I think the solution lies within that idea.  

The problem so far with bottom nav implementations is you have a structure like this:
```
- Scaffold / PSC 
    - BottomNavigation -- Stack
          - Scaffold / PSC
               - Your page
```
So the BottomNav implementation uses as IndexStack that lies on top of a Scaffold and the clicks just don't pass to where you want them to.   

Quite a few people have brought this up with flutter team, with ideas to allow us to access the root PSC, but that too is imperfect.  Ive manually accessed the PSC before setting up a BottomNavigationBar and then passed it into the various tabs, and then the scroll to top does work, but then the problem is every list in every tab simultaneous scroll up, so that is also useless.

Whats interesting is things like `WebView` and InAppWebView work perfectly no mater where you put them in the tree, so I believe they are doing something along the lines of what you have mentioned.  And of course CupertinoTabScaffold/CupertinoTabBar doesn't have this issue

**Comment by wwwdata** [comment]
> Thanks for everyone work on this issue.  Solving this would make go_router _the_ router to use.
> 
> 
> 
> One issue with other implementations of BottomNavigation and IndexedStacks is that on iOS you lose access to the scroll-to-top with status bar tap functionality.  This is because of issues with the PrimaryScrollController from a root stack eating up those clicks.  And if you try to pass PSC to all the different stacks then they all scroll up.
> 
> 
> 
> So far using CupertinoTabScaffold/CupertinoTabBar doesn't seem to carry the problem (but has so many other problems with routers).
> 
> 
> 
> Just throwing this out there as something to keep in mind with your implementations.  If its working with your implementation, then mores the better!
> 
> 
> 
> On the edge of my app to see if this comes to go_router as everything else seems to work really well and _easy_

I could easily solve the scroll to top problem by using the following package: https://pub.dev/packages/scrolls_to_top

**Comment by tananga** [comment]
@csells  We need something like this: https://youtu.be/9oH42_Axr3Q.
